theme: 'hugo-theme-stack'

params:
  widgets:
    homepage:
        - type: search
        - type: archives
          params:
              limit: 5
        - type: categories
          params:
              limit: 10
        - type: tag-cloud
          params:
              limit: 10
    page:
        - type: toc
      
